app = 'graphql-workshop'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "10s"
  path = "/"

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_GRAPHQL_ENDPOINT = "https://graphql-workshop.fly.dev/graphql"
  NEXT_PUBLIC_GRAPHQL_WS_ENDPOINT = "wss://graphql-workshop.fly.dev/graphql"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
