app = "graphql-workshop"
primary_region = "iad"

[build]
  dockerfile = "server/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "4000"
  MESSAGE_HISTORY_LIMIT = "500"
  DATABASE_URL = "file:/data/dev.db"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "data"
  destination = "/data"
